//> using toolkit 0.4.0
//> using dep "com.lihaoyi::scalatags:0.13.1"
//> using dep "org.ocpsoft.prettytime:prettytime:5.0.4.Final"
//> using dep "com.softwaremill.ox::core:0.3.1"
//> using dep "com.softwaremill.sttp.tapir::tapir-netty-server-sync:1.10.14"
//> using dep "com.softwaremill.sttp.openai::core:0.2.0"
//> using dep "com.github.eikek::yamusca-core:0.10.0"
//> using dep "com.outr::scribe:3.15.0"
//> using dep "org.slf4j:slf4j-simple:2.0.13"
//> using jvm 21
//> using packaging.dockerFrom ghcr.io/fazzou/ydr-base
//> using packaging.dockerImageRepository fazzou/ydr
//> using packaging.dockerImageRegistry ghcr.io
